blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views as blog_views





urlpatterns = [
    url(r'^$', blog_views.blog_page,name='blogs'),
    # url(r'^(?P<id>\d+)/$', article,name='article'),
    # url('^search/', search_blog, name='search_blog'),
    # url('(?P<name>[\w-]+)/$', search_category, name='search_category')


]

calmm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from home import views as home_views
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/', include("home.urls", namespace='home')),
    url(r'^shop/$', home_views.shop_page, name='shop'),
    url('shop/(?P<name>[\w-]+)/$', home_views.shop_product_category, name='shop_product_category'),
    url(r'^blog/', include("blog.urls", namespace='blog')),
    url(r'^about/$', home_views.about_page, name='about'),
    url(r'^contact/$', home_views.contact, name='contact_us'),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from home import views as home_views



urlpatterns = [
url(r'^/', home_views.home_page, name='index'),
url('(?P<name>[\w-]+)/$', home_views.product_category, name='product_category')
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Blog(models.Model):
    username = models.CharField(max_length=20)
    user_image = models.FileField(upload_to='user/%Y/%m/%d/')
    title = models.CharField(max_length=20)
    content = models.TextField(max_length=2000)
    posted_on = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)


    def __unicode__(self):
        return self.title

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    def __unicode__(self):
        return self.name

class Gender_category(models.Model):
        name = models.CharField(max_length=5)

        def __unicode__(self):
            return self.name

class Products(models.Model):
    title = models.CharField(max_length=30)
    # content = models.TextField(max_length=2000)
    image = models.FileField(upload_to='products/%Y/%m/%d/')
    category = models.ForeignKey(Category, null=True)
    gender_category = models.ForeignKey(Gender_category, null=True)
    # original_price = models.DecimalField( max_digits=10, decimal_places=2)
    # selling_price = models.DecimalField(max_digits=10, decimal_places=2)
    posted_on = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)


    def __unicode__(self):
        return self.title

class Home_blog(models.Model):
    username = models.CharField(max_length=20)
    user_image = models.FileField(upload_to='user/%Y/%m/%d/')
    title = models.CharField(max_length=20)
    content = models.TextField(max_length=2000)
    posted_on = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)


    def __unicode__(self):
        return self.title


class Contact (models.Model):
    name = models.CharField (max_length=20)
    email = models.EmailField(max_length=70, blank=True,  null= True)
    message = models.TextField()
    sent_on = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)

    def __unicode__(self):
        return self.name

home/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        exclude = ()

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from home.models import *
from django.shortcuts import render

# Create your views here.

def blog_page (request):
    if request.method == 'GET':
        blog = Home_blog.objects.all()

        context = {
            'blog': blog,
        }
        return render(request, 'blog/blog.html', context)

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from models import *
from .forms import *
from django.utils import timezone

# Create your views here.

def home_page(request):
    if request.method == 'GET':
        # product_list = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on')
        product_latest = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-id')[:8]
        cat = Category.objects.all()
        blog = Home_blog.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on').order_by('-id')[:3]

        context = {
            # 'product_list': product_list,
            'product_latest': product_latest,
            'cat': cat,
            'blog': blog,


        }
        return render(request, 'home/index.html', context)



def product_category(request, name=None):
    # product_list = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on')
    product_latest = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-id')[:8]
    cat = Category.objects.all()
    blog = Home_blog.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on').order_by('-id')[:3]
    this_cat = get_object_or_404(cat, name=name)
    posts_cat = Products.objects.filter(category=this_cat.id).filter(posted_on__lte=timezone.now()).order_by('-posted_on').order_by('-id')[:8]



    context = {
        # 'product_list': product_list,
        'product_latest': posts_cat,
        'cat': cat,
        'blog': blog,
        'current_category': name,

    }
    return render(request, 'home/index.html', context)





def shop_page(request):
    if request.method == 'GET':
        product_list = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on')
        cat = Category.objects.all()
        context = {
            'product_list': product_list,
            'cat': cat,


        }
        return render(request, 'home/shop.html', context)


def shop_product_category(request, name=None):
    product_list = Products.objects.filter(posted_on__lte=timezone.now()).order_by('-posted_on')
    cat = Category.objects.all()
    blog = Home_blog.objects.all()
    this_cat = get_object_or_404(cat, name=name)
    posts_cat = Products.objects.filter(category=this_cat.id).filter(posted_on__lte=timezone.now()).order_by('-posted_on')



    context = {
        'product_list': posts_cat,
        'cat': cat,
        'blog': blog,
        'current_category': name,

    }
    return render(request, 'home/shop.html', context)


def about_page(request):
        return render(request, 'home/about.html')

def contact(request):

    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            print 'saved'
            return render(request, 'home/index.html')
        else:
            print 'error sent'
            return render(request, 'home/index.html', {'form' : form, 'contact' : True })
    else:
        print 'nothing'
        return render(request, 'home/index.html', { 'contact' : True })

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <title>{% block title %} CALMMCALMM {% endblock title %}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--Import fontawesome stylesheet-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/medium.css' %}">
    <link rel="stylesheet" href="{% static 'css/medium_and_below.css' %}">
    <link rel="stylesheet" href="{% static 'css/small_screen.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>


<body>

<nav>
    <div class="nav-wrapper white navigation hide-on-small-only">
        <span class="logo-holder">
                    <a href="{% url 'home:index' %}" class="no-decoration"><img src="/static/images/logo-preview.jpg" alt="logo" class="brand-logo-img "> </a>

        </span>

        <ul class="left hide-on-med-and-down">
            <li ><a class='black-text text-blue-ligten-2 {% if home_page %} nav-active {% endif %}' href="{% url 'home:index' %}">Home</a></li>
            <li><a class='black-text text-blue-ligten-2 ' href="{% url 'shop' %}">SHOP</a></li>
            <li><a class='black-text text-blue-ligten-2 ' href="{% url 'blog:blogs' %}">BLOG</a></li>
            <li ><a class='black-text text-blue-ligten-2 ' href="{% url 'about' %}">ABOUT</a></li>
            <li ><a target="_self"  href="#modal1" data-activates="slide-out" class="black-text text-blue-ligten-2 collapse modal-trigger">CONTACT</a></li>
        </ul>
    </div>
    <div class="row navigation hide-on-med-only hide-on-large-only" id="customNavbar">
        <div class="col s4">
            <a class="btn btn-floating  white-text waves-effect waves-light button-collapse left sidenav-trigger" data-target="slide-out"><i class="material-icons">menu</i>
            </a>
        </div>
        <div class="col s4 center">
            <a href="{% url 'home:index' %}" class="no-decoration"><img src="/static/images/logo-preview.jpg" alt="logo"  class="brand-logo-img"></a>
        </div>
        <div class="col s4">

        </div>
    </div>
</nav>


<ul id="slide-out" class="sidenav">
    <li>
        <h3 class="center">
            <a href="{{% url 'home:index' %}" class="no-decoration"><img src="/static/images/logo-preview.jpg" alt="logo"  class="brand-logo-img"></a>
        </h3>
        <hr>
    </li>
    <br>
    <li ><a class='black-text text-blue-ligten-2 {% if home_page %} nav-active {% endif %}' href="{% url 'home:index' %}">HOME</a></li>
    <li><a class='black-text text-blue-ligten-2' href="{% url 'shop' %}">SHOP</a></li>
    <li><a class='black-text text-blue-ligten-2' href="{% url 'blog:blogs' %}">BLOG</a></li>
    <li><a class='black-text text-blue-ligten-2' href="{% url 'about' %}">ABOUT</a></li>
    <li ><a target="_self"  href="#modal1" data-activates="slide-out" class="black-text text-blue-ligten-2 collapse modal-trigger">CONTACT</a></li>
</ul>

 <!-- Modal Structure -->
    <div id="modal1" class="modal bottom-sheet">
        <div class="modal-content">
            <!--<div class="chip">-->
                <!--<img src="/static/images/sample.JPG" alt="Contact Person">Get in touch</div>-->
            <div class="row">
                <div class="col s12">
                    <form method="post" action="{% url 'contact_us' %}" >{% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">account_circle</i>
                                <input id="icon_prefix" type="text" class="validate" name="name">
                                <label for="icon_prefix">Your name</label>
                            </div>
                            {{form.name.errors}}

                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">email</i>
                                <input id="email" type="email" class="validate" name="email">
                                <label for="email" data-error="Invalid email" data-success="Valid">Your email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">mode_edit</i>
                                <textarea id="icon_prefix2" class="materialize-textarea" name="message"></textarea>
                                <label for="icon_prefix2">Message</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12 right">
                                <div class="modal-footer">
                                    <button class="btn waves-effect waves-light pulse" type="submit" name="action">Submit
                                        <i class="material-icons right"  onclick="Materialize.toast('{{form.errors}}', 4000,'rounded')">send</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% block content %}

{% endblock content %}

<footer class="page-footer white black-text">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <div class="footer-logo">
                    <img src="/static/images/logo-preview.jpg" alt="logo">
                </div>

                <h5 >Follow us on</h5>
                <!--<a href="#" class="fa fa-facebook"></a> |-->
                <!--<a href="#" class="fa fa-twitter"></a> |-->
                <a href="https://www.instagram.com/calmmcalmm_/" target="_blank" class="fa fa-instagram" title="Instagram"></a>


            </div>
            <div class="col l6 s12">
                <h5 class="">CONCIERGE</h5>
                <p>Don't hesitate in contacting us for any questions you might have.</p>
                <div class="row">
                    <div class="col s1">
                        <ul>
                            <li><i href="" class="fa fa-question"></i></li>
                            <li><i href="" class="fa fa-envelope"></i></li>
                            <li><i href="" class="fa fa-phone"></i></li>
                            <li><i href="" class="fa fa-location-arrow"></i></li>
                        </ul>
                    </div>
                    <div class="col s11">
                        <ul>
                            <li><i href="" class=""> FREQUENTLY ASKED QUESTIONS</i></li>
                            <li><i href="" class=""> +82 010 2113 4938</i></li>
                            <li><i href="" class=""> hongddo12@gmail.com</i></li>
                            <li><i href="" class=""> 서울시 은평구 신사동 23-23번지 3층 301호 (증산로 471-5)</i></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container black-text">
            © 2018 Copyright
            <!--<a class="grey-text  right" href="#!">More</a>-->
        </div>
    </div>
</footer>




<!--Import jQuery before materialize.js-->
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>
<!--<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>-->
<!--<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>-->

<script>
    $(document).ready(function(){
        $('.sidenav').sidenav();
    });
</script>

<script>
    $(document).ready(function(){
        $('.slider').slider();
    });

</script>
<script>
    $(document).ready(function(){
        $('.carousel.carousel-slider').carousel({
            indicators: true
        });
    });
</script>
<script>
    $(document).ready(function(){
        $('.parallax').parallax();
    });
</script>

<script>
    $(document).ready(function(){
        $('.fixed-action-btn').floatingActionButton();
    });

</script>

<script>
  $(document).ready(function(){
    $('.modal').modal();
  });

</script>




{% block script %}

{% endblock script %}



</body>
</html>

templates/blog/blog.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}


<div class="row container">
    <div class="col s12">
        <h5 class="center">BLOGS</h5>
        <p class="center">This unique jewelry is handcrafted on the beautiful island of Nantucket using fine silver and semi precious stones.
            View glasse fashion collection 2018 by Fanbong</p>
    </div>
</div>

<div class="row news">
    <div class="col s12">
        <div class="row">
            {% if blog %}
            {% for obj in blog %}
            <div class="col s12 m6 l4">
                <div class="card">
                    <div class="card-image_a waves-effect waves-block waves-light">
                        <img class="activator" src="{{obj.user_image.url}}" >
                    </div>
                    <div class="card-content">
                        <!--<span class="card-title activator grey-text text-darken-4">Title<i class="material-icons right">more_vert</i></span>-->
                        <p><i href="" class="fa fa-user"> {{obj.username}}</i> | <i href=""class="fa fa-calendar"> {{obj.posted_on}}</i></p>
                        <span class="card-title">{{obj.title|truncatechars:50}}</span>
                        <p>{{obj.content|truncatechars:40}}</p>
                        <p href="" class=" activator red-text text-darken-4">Read more<i class="material-icons right">more_vert</i></p>
                    </div>
                    <div class="card-reveal">
                        <span  class="card-title grey-text text-darken-4">{{obj.title}}<i class="material-icons right">close</i></span>
                        <p>{{obj.content}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="center">No products found for this category</h2>
            <p class="center">Kindly visit again later</p>
            {% endif %}
        </div>
    </div>
</div>


{% endblock content %}


{% block script %}

{% endblock script %}

templates/home/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}


<div class="row container">
    <div class="col s12">
        <h5 class="center">ABOUT US</h5>
        <p class="center">This unique jewelry is handcrafted on the beautiful island of Nantucket using fine silver and semi precious stones.
            View glasse fashion collection 2018 by Fanbong</p>
    </div>
</div>

    <div class="parallax-container">
      <div class="parallax"><img src="/static/images/banner2.jpg"></div>
    </div>


{% endblock content %}


{% block script %}

{% endblock script %}

templates/home/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}


<div class="row">
    <!--<div class="col s12">-->
    <div class="carousel carousel-slider">
        <a class="carousel-item" href="#one!"><img src="/static/images/head%20image%201.png"></a>
        <a class="carousel-item" href="#two!"><img src="/static/images/head%20image%202.jpg"></a>
        <a class="carousel-item" href="#three!"><img src="/static/images/head%20image%203.jpg"></a>
    </div>
    <!--</div>-->
</div>

<div class="row news">
    <div class="col s12 m4  center ">
        <img src="/static/images/left.jpg" alt="Avatar" class="style_prevu_kit">
    </div>
    <div class="col s12 m4  center">
        <img src="/static/images/middle.jpg" alt="Avatar" class="style_prevu_kit">
    </div>
    <div class="col s12 m4  center">
        <img src="/static/images/right.jpg" alt="Avatar" class="style_prevu_kit">
    </div>
</div>

<div class="row container">
    <div class="col s12">
        <h5 class="center">BEST SELLERS</h5>
        <p class="center">This unique jewelry is handcrafted on the beautiful island of Nantucket using fine silver and semi precious stones.
            View glasse fashion collection 2018 by Fanbong</p>
    </div>
</div>

<div class="row container">
    <div class="col s12 center">
        {% if cat %}
        {% for obj in cat %}
        <a href="{% url 'home:product_category' name=obj.name %}" class="{% if current_category == obj.name %} active {% endif %} waves-effect waves-teal btn-flat">{{obj.name}}</a>
        {% endfor %}
        {% else %}
        <p class="center">No categories</p>
        {% endif %}
    </div>
</div>

<div class="row slide_a">
    <div class="col s12">
        <div class="row">
            {% if product_latest %}
            {% for obj in product_latest %}
            <div class="col s12 m4 l3">
                <div class="card">
                    <div class="card-image">
                        <img src="{{obj.image.url}}" class="responsive-img materialboxed">
                        <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add_shopping_cart</i></a>
                    </div>
                    <div class="card-content">
                        <p>{{obj.gender_category}}</p>
                    </div>
                    <div class="card-action grey-text">
                        <span class="card-title ">{{obj.title}}</span>
                        <br>
                        <!--<p><strike>${{obj.original_price}}</strike>  ${{obj.selling_price}}</p>-->
                        <!--<a href="#">Link</a>-->
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="center">No products found for this category</h2>
            <p class="center">Kindly visit again later</p>
            {% endif %}
        </div>
    </div>
</div>


<div class="row container">
    <div class="col s12 center">
        <a class="waves-effect waves-light " href="{% url 'shop' %}" ><i class="material-icons right">more_horiz</i>Shop More</a>
    </div>
</div>


<div class="row">
    <div class="col s12">
        <div class="banner">
            <img src="/static/images/banner1.jpg">
        </div>
    </div>
</div>




<div class="row container">
    <div class="col s12">
        <h5 class="center">LATEST NEWS FROM THE BLOG</h5>
        <p class="center">This unique jewelry is handcrafted on the beautiful island of Nantucket using fine silver and semi precious stones.
            View glasse fashion collection 2018 by Fanbong</p>
    </div>
</div>

<div class="row news">
    <div class="col s12">
        <div class="row">
            {% if blog %}
            {% for obj in blog %}
            <div class="col s12 m6 l4">
                <div class="card">
                    <div class="card-image_a waves-effect waves-block waves-light">
                        <img class="activator" src="{{obj.user_image.url}}" >
                    </div>
                    <div class="card-content">
                        <!--<span class="card-title activator grey-text text-darken-4">Title<i class="material-icons right">more_vert</i></span>-->
                        <p><i href="" class="fa fa-user"> {{obj.username}}</i> | <i href=""class="fa fa-calendar"> {{obj.posted_on}}</i></p>
                        <span class="card-title">{{obj.title|truncatechars:50}}</span>
                        <p>{{obj.content|truncatechars:40}}</p>
                        <p href="" class=" activator red-text text-darken-4">Read more<i class="material-icons right">more_vert</i></p>
                    </div>
                    <div class="card-reveal">
                        <span  class="card-title grey-text text-darken-4">{{obj.title}}<i class="material-icons right">close</i></span>
                        <p>{{obj.content}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="center">No products found for this category</h2>
            <p class="center">Kindly visit again later</p>
            {% endif %}
        </div>
    </div>
</div>





{% endblock content %}


{% block script %}

{% endblock script %}

templates/home/shop.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}


<div class="row container">
    <div class="col s12">
        <h5 class="center">BEST PRODUCTS</h5>
        <p class="center">This unique jewelry is handcrafted on the beautiful island of Nantucket using fine silver and semi precious stones.
            View glasse fashion collection 2018 by Fanbong</p>
    </div>
</div>

<div class="row container">
    <div class="col s12 center">
        {% if cat %}
        {% for obj in cat %}
        <a href="{% url 'shop_product_category' name=obj.name %}" class="{% if current_category == obj.name %} active {% endif %} waves-effect waves-teal btn-flat">{{obj.name}}</a>
        {% endfor %}
        {% else %}
        <p class="center">No categories</p>
        {% endif %}
    </div>
</div>

<div class="row container">
    <div class="col s12">
        <div class="row">
            {% if product_list %}
            {% for obj in product_list %}
            <div class="col s12 m6 l4">
                <div class="card">
                    <div class="card-image">
                        <img src="{{obj.image.url}}" class="responsive-img materialboxed">
                        <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add_shopping_cart</i></a>
                    </div>
                    <div class="card-content">
                        <p>{{obj.gender_category}}</p>
                    </div>
                    <div class="card-action grey-text">
                        <span class="card-title ">{{obj.title}}</span>
                        <br>
                        <!--<p><strike>${{obj.original_price}}</strike>  ${{obj.selling_price}}</p>-->
                        <!--<a href="#">Link</a>-->
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h2 class="center">No products found for this category</h2>
            <p class="center">Kindly visit again later</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}


{% block script %}

{% endblock script %}